# Generated by Django 5.2.8 on 2026-02-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('Friends', 'Friends'), ('Work', 'Work'), ('Family', 'Family'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
